apiVersion: v1
kind: Service
metadata:
     name: cas-service
     annotations:
       kubernetes.io/service-name="cas-service"
     labels:
       app: cas
spec:
     selector:
       app: cas
       version: v1
     ports:
      - port: 80
        targetPort: 8080  
